kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: cp
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
    - docker cp . airflow:/opt/bitnami/airflow/
    - docker exec --user root airflow chown -R airflow:airflow /opt/bitnami/airflow/

volumes:
- name: dockersock
  host:
    path: /volume1/docker/config/docker.sock